# -*- coding: utf-8 -*-
"""copy yolo_train_roboflow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jfhrsZ0SJSBxRnlNfArlWkwINW2PFRdE
"""

!pip install ultralytics roboflow -q

# Підключаємо Google Диск
from google.colab import drive
drive.mount('/content/drive')

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="qMYp9paCaHaBmauWo0Yo")
project = rf.workspace("yolo-ybhhs").project("dataset-bounding-box-drones")
version = project.version(3)
dataset = version.download("yolov8")

from ultralytics import YOLO



model = YOLO("yolov8n.pt")



model.train(
    data=f"{dataset.location}/data.yaml",
    epochs=10,
    imgsz=640,
    batch=8,
)

print(" Навчання завершено! ")

import glob
import os
# from google.colab import files  # Специфічно для Colab, на локальному ПК не потрібно
from ultralytics import YOLO

#  НАЛАШТУВАННЯ
# Вкажіть шлях до вашого відео файлу
video_path = "video_test.mp4"

print(" Починаю обробку")

#  ЗАВАНТАЖЕННЯ МОДЕЛІ ДЛЯ ГУГЛ КОЛАБ
# all_folders = glob.glob("/content/runs/detect/train*")
# latest_folder = max(all_folders, key=os.path.getctime)
# weights = latest_folder + "/weights/best.pt"

# Для Локального запуску ми просто вказуємо шлях до ваг:
weights = "best.pt"  # Переконайтеся, що файл best.pt знаходиться в тій самій папці де і код
print(f"Завантажую ваги: {weights}")

model = YOLO(weights)

results = model(video_path, save=True, conf=0.3, stream=True)

for r in results:
    pass

print("Готово! Відео з детекцією збережено у папці 'runs/detect/predict'.")

# --- СКАЧУВАННЯ (Тільки для Colab) ---
# all_predict_folders = glob.glob("/content/runs/detect/predict*")
# latest_predict_folder = max(all_predict_folders, key=os.path.getctime)
# base_name = os.path.splitext(os.path.basename(video_path))[0]
# saved_video_path = f"{latest_predict_folder}/{base_name}.avi"
# files.download(saved_video_path)